defaults:
  - env/generation_reward@env.train
  - env/generation_reward@env.eval
  - model/wan22_ti2v_5b@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - weight_syncer/patch_syncer@weight_syncer
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/
    - file://${oc.env:REPO_PATH}/examples/embodiment/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "ocr_nft_wan22_ti2v_5b_compile_lr4e4_clip02_tau0_50"
    logger_backends: ["tensorboard"]
  max_epochs: 70
  max_steps: -1
  only_eval: False
  val_check_interval: -1
  save_interval: -1
  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: False
  kl_penalty: kl
  kl_penalty_type: kl

  group_size: 24
  reward_coef: 1.0
  rollout_epoch: 6
  eval_rollout_epoch: 8

  reward_type: chunk_level
  logprob_type: token_level
  entropy_type: token_level
  update_epoch: 1
  adv_type: grpo
  loss_type: embodied_nft
  loss_agg_func: "token-mean"

  kl_beta: 0.0
  entropy_bonus: 0.0
  clip_ratio_high: 0.0001
  clip_ratio_low: 0.0001
  clip_ratio_c: null
  gamma: 1.0
  gae_lambda: 1.0
  filter_rewards: False

  nft_loss_form: mse
  nft_beta: 0.1
  adv_clip_max: 5.0
  dpo_beta: 1.0
  nft_weight_mode: adaptive
  nft_weight_scale: 1.0
  nft_target_space: x0
  nft_xcur_source: resample
  nft_tau: [1.0, 0.01, 0, 70]
  nft_clip_ratio: 0.1
  recompute_v: False
  nft_gather_type: action_level
  nft_energy_reduction: mean

  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 1.0
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False
  train:
    total_num_envs: 192
    group_size: ${algorithm.group_size}
    max_episode_steps: 1
    max_steps_per_rollout_epoch: 1
    video_cfg:
      save_video: False
    dataset:
      type: "generation.ocr_dataset"
      path: "/mnt/public2/chenkang/wam_rl/video_rl/DiffusionNFT/dataset/ocr"
      split: "train"
    reward:
      type: "generation.ocr"
      key: "avg"
      use_gpu: False
      lang: "en"
  eval:
    total_num_envs: 128
    group_size: 1
    max_episode_steps: 1
    max_steps_per_rollout_epoch: 1
    is_eval: True
    dataset:
      type: "generation.ocr_dataset"
      path: "/mnt/public2/chenkang/wam_rl/video_rl/DiffusionNFT/dataset/ocr"
      split: "test"
    reward:
      type: "generation.ocr"
      key: "avg"
      use_gpu: False
      lang: "en"

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  recompute_logprobs: False
  collect_prev_infos: True
  enable_offload: True
  pipeline_stage_num: 1
  model:
    model_path: ${actor.model.model_path}
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 4
  global_batch_size: 576
  seed: 42
  enable_offload: False

  model:
    model_path: "/mnt/public2/chenkang/wam_rl/checkpoints/Wan2.2-TI2V-5B-Diffusers"
    precision: "bf16"
    wan22_ti2v_5b:
      rl_mode: nft
      resolution: [512, 512]
      num_frames: 1
      num_steps: 10
      eval_num_steps: 20
      timestep_fraction: 0.99
      guidance_scale: 1.0
      eval_guidance_scale: 1.0
      cfg: False
      max_sequence_length: 256
      output_type: "pt"
      use_lora: True
      lora_rank: 32
      lora_alpha: 64
      lora_path: null
      offload_auxiliary_modules: False
      compile_transformer_forward: True
      compile_mode: "default"

  optim:
    lr: 4.0e-4
    value_lr: 3.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    weight_decay: 1.0e-4
    clip_grad: 1.0
    critic_warmup_steps: 0

  fsdp_config:
    strategy: "fsdp2"
    sharding_strategy: "full_shard"
    use_orig_params: True
    gradient_checkpointing: True
    gradient_checkpointing_use_reentrant: False
    enable_gradient_accumulation: True
    reshard_after_forward: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
