env_type: "gen_reward"
seed: 42
total_num_envs: 24
group_size: 3
auto_reset: False
ignore_terminations: False
max_episode_steps: 1
max_steps_per_rollout_epoch: 5
is_eval: False

video_cfg:
  save_video: False
  info_on_video: False
  video_base_dir: ${runner.logger.log_path}/video/ocr_video_reward
  image_frame_repeat: 8
  num_capture_samples: 3

dataset:
  type: "generation.ocr_dataset"
  path: "/mnt/public2/chenkang/wam_rl/video_rl/flow_grpo/dataset/ocr"
  split: "train"

reward:
  type: "generation.video_ocr"
  key: "avg"
  use_gpu: False
  lang: "en"
  frame_interval: 4
